trigger:
- main

pr:
- '*'

jobs:
- job: Build
  displayName: 'Build job'
  pool:
    name: testing ## Ketu po perdor self-hosted agent per ti ber run job. e kam instaluar ne 1 vm me ubuntu OS
  steps:
  - checkout: self
    persistCredentials: true

  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build --if-present
    displayName: 'npm install and build'

  - publish: $(System.DefaultWorkingDirectory)
    artifact: 'node-app'

- job: Deploy
  displayName: 'Deploy to Azure Web App'
  pool:
    name: testing
  dependsOn: Build
  steps:
  - download: current
    artifact: node-app

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1 (a73c2dc9-f21b-41c9-8802-d3f1584dbe2d)'
      appType: 'webAppLinux'
      WebAppName: 'polymaths'
      deployToSlotOrASE: true
      ResourceGroupName: 'polymaths_group'
      SlotName: 'production'
      packageForLinux: '$(Pipeline.Workspace)/node-app'
      RuntimeStack: 'NODE|16-lts'
      StartupCommand: 'node index.js'
